language: ruby
rvm:
  - 2.2
before_script:
  - rake install
script:
  - pdf_xcassets
  - pdf_xcassets 1
  - pdf_xcassets 1 2
  - pdf_xcassets resources test/fixtures
  - ruby test/pdf_xcassets_test.rb
